/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tx_hier.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2ddea573fde245046ca95c75f388c35f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbs2tx/tx_hier.h>
// pydoc.h is automatically generated in the build directory
#include <tx_hier_pydoc.h>

void bind_tx_hier(py::module& m)
{

    using tx_hier = gr::dvbs2tx::tx_hier;


    py::class_<tx_hier, gr::hier_block2, gr::basic_block, std::shared_ptr<tx_hier>>(
        m, "tx_hier", D(tx_hier))

        .def(py::init(&tx_hier::make),
             py::arg("framesize"),
             py::arg("rate"),
             py::arg("constellation"),
             py::arg("pilots"),
             py::arg("goldcode"),
             py::arg("rolloff"),
             py::arg("dummyframes"),
             D(tx_hier, make))


        ;
}
